<?php
/**
 * Uninstall Script for SEOgen Plugin
 * 
 * This file is executed when the plugin is deleted from WordPress.
 * It removes all generated pages and cleans up plugin data.
 * 
 * @package SEOgen
 */

// Exit if accessed directly or not during uninstall
if ( ! defined( 'WP_UNINSTALL_PLUGIN' ) ) {
	exit;
}

/**
 * Delete all pages generated by SEOgen
 */
function seogen_delete_generated_pages() {
	global $wpdb;
	
	// Query all posts with the _hyper_local_managed meta key
	$generated_post_ids = $wpdb->get_col(
		"SELECT post_id FROM {$wpdb->postmeta} WHERE meta_key = '_hyper_local_managed' AND meta_value = '1'"
	);
	
	if ( empty( $generated_post_ids ) ) {
		return;
	}
	
	// Delete each post permanently (bypass trash)
	foreach ( $generated_post_ids as $post_id ) {
		// Delete all post meta
		$wpdb->delete( $wpdb->postmeta, array( 'post_id' => $post_id ), array( '%d' ) );
		
		// Delete the post itself
		wp_delete_post( $post_id, true );
	}
}

/**
 * Delete all plugin options from the database
 */
function seogen_delete_plugin_options() {
	// Settings and configuration
	delete_option( 'seogen_settings' );
	delete_option( 'seogen_business_config' );
	
	// Cached data
	delete_option( 'hyper_local_services_cache' );
	delete_option( 'hyper_local_cities_cache' );
	delete_option( 'hyper_local_hubs_cache' );
	
	// Any transients (temporary data)
	global $wpdb;
	$wpdb->query(
		"DELETE FROM {$wpdb->options} WHERE option_name LIKE '_transient_seogen_%' OR option_name LIKE '_transient_timeout_seogen_%'"
	);
	$wpdb->query(
		"DELETE FROM {$wpdb->options} WHERE option_name LIKE '_transient_hyper_local_%' OR option_name LIKE '_transient_timeout_hyper_local_%'"
	);
}

/**
 * Delete custom post type if registered
 */
function seogen_delete_custom_post_type() {
	// Unregister the custom post type
	unregister_post_type( 'service_page' );
	
	// Flush rewrite rules to clean up permalinks
	flush_rewrite_rules();
}

/**
 * Main uninstall routine
 */
function seogen_uninstall() {
	// Delete all generated pages
	seogen_delete_generated_pages();
	
	// Delete plugin options
	seogen_delete_plugin_options();
	
	// Clean up custom post type
	seogen_delete_custom_post_type();
}

// Execute uninstall
seogen_uninstall();
