<?php
/**
 * City Hub Quality Improvement Helpers
 * 
 * Helper functions for improving City Hub page output quality:
 * - Parent hub link generation and positioning
 * - City name repetition reduction
 * - Duplicate FAQ heading removal
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

trait SEOgen_Admin_City_Hub_Helpers {

	/**
	 * Get city-specific differentiator templates
	 * 
	 * Returns array of local differentiator sentences that add city-specific context
	 * without referencing specific landmarks or making unverifiable claims.
	 * 
	 * @param string $vertical Business vertical (electrician, plumber, etc.)
	 * @param string $hub_key Hub key (residential, commercial)
	 * @return array Array of differentiator templates with {city} placeholder
	 */
	private function get_city_differentiator_templates( $vertical = '', $hub_key = '' ) {
		// DISABLED: City differentiators are now generated by the backend AI
		// This function returns empty array to prevent injecting hardcoded content
		// that may not match the business vertical
		return array();
	}
	
	/**
	 * Select city differentiator deterministically
	 * 
	 * Uses hash of hub_key + city_slug to select a differentiator template,
	 * ensuring the same city always gets the same differentiator.
	 * 
	 * @param string $hub_key Hub key
	 * @param string $city_slug City slug
	 * @param string $city_name City display name
	 * @param string $vertical Business vertical
	 * @return string City-specific differentiator sentence
	 */
	private function select_city_differentiator( $hub_key, $city_slug, $city_name, $vertical = '' ) {
		$templates = $this->get_city_differentiator_templates( $vertical, $hub_key );
		
		// Return empty string if no templates (backend AI handles all content now)
		if ( empty( $templates ) ) {
			return '';
		}
		
		// Deterministic selection using hash
		$hash = md5( $hub_key . '_' . $city_slug );
		$index = hexdec( substr( $hash, 0, 8 ) ) % count( $templates );
		
		$template = $templates[ $index ];
		
		// Replace {city} placeholder with actual city name
		return str_replace( '{city}', $city_name, $template );
	}
	
	/**
	 * Get intro enhancement sentence templates
	 * 
	 * Returns pool of explanatory sentences that can be appended to generic
	 * City Hub intro paragraphs to add local context and reduce templated feel.
	 * 
	 * @return array Array of enhancement sentence templates
	 */
	private function get_intro_enhancement_templates() {
		return array(
			'Many homes in the area were built decades ago, making safe electrical capacity, system updates, and code compliance especially important.',
			'As energy usage increases with modern appliances and technology, electrical system upgrades help ensure safety and reliability.',
			'Older properties often benefit from electrical assessments to identify potential safety concerns and capacity limitations.',
			'Keeping electrical systems current with building codes and safety standards helps protect property and occupants.',
			'Modern electrical demands from HVAC, kitchen equipment, and smart home devices often require system capacity evaluations.',
			'Professional electrical service helps property owners maintain safe, code-compliant systems that meet current usage needs.',
			'Electrical safety inspections and upgrades are increasingly common as properties age and usage patterns change.',
			'Proper electrical maintenance and timely upgrades help prevent hazards and ensure systems can handle modern power demands.',
			'Many properties need electrical work to support renovations, equipment additions, or to address aging infrastructure.',
			'Electrical system reliability becomes especially important as homes and businesses depend more heavily on powered equipment.',
			'Code-compliant electrical work ensures systems are installed safely and meet local building requirements.',
			'As electrical technology evolves, professional service helps properties stay current with safety standards and best practices.',
		);
	}
	
	/**
	 * Detect if intro paragraph is overly generic
	 * 
	 * Flags paragraph as generic if 2+ of the following criteria are met:
	 * A) Contains generic service phrases
	 * B) Lacks explanatory context terms
	 * C) Is very short (≤2 sentences)
	 * 
	 * @param string $paragraph_text Paragraph text (HTML stripped)
	 * @return bool True if paragraph is generic and needs enhancement
	 */
	private function is_generic_intro_paragraph( $paragraph_text ) {
		$text_lower = strtolower( $paragraph_text );
		$criteria_met = 0;
		
		// Criterion A: Contains generic service phrases
		$generic_phrases = array(
			'we provide',
			'we offer',
			'serving homeowners',
			'serving residents',
			'serving businesses',
			'throughout',
		);
		
		$has_generic_phrase = false;
		foreach ( $generic_phrases as $phrase ) {
			if ( false !== strpos( $text_lower, $phrase ) ) {
				$has_generic_phrase = true;
				break;
			}
		}
		
		if ( $has_generic_phrase ) {
			$criteria_met++;
		}
		
		// Criterion B: Lacks explanatory context terms
		$explanatory_terms = array(
			'safety',
			'capacity',
			'compliance',
			'upgrade',
			'modernization',
			'demand',
			'older',
			'load',
			'inspection',
			'code',
			'hazard',
			'reliable',
			'protect',
		);
		
		$has_explanatory_term = false;
		foreach ( $explanatory_terms as $term ) {
			if ( false !== strpos( $text_lower, $term ) ) {
				$has_explanatory_term = true;
				break;
			}
		}
		
		if ( ! $has_explanatory_term ) {
			$criteria_met++;
		}
		
		// Criterion C: Very short (≤2 sentences)
		$sentence_count = preg_match_all( '/[.!?]+/', $paragraph_text );
		if ( $sentence_count <= 2 ) {
			$criteria_met++;
		}
		
		// Flag as generic if 2+ criteria met
		return $criteria_met >= 2;
	}
	
	/**
	 * Enhance generic City Hub intro paragraph
	 * 
	 * Appends explanatory sentence to generic intro paragraphs to add local
	 * context and reduce templated feel. Does NOT replace original content.
	 * 
	 * @param string $markup Gutenberg markup
	 * @param string $hub_key Hub key for deterministic selection
	 * @param string $city_slug City slug for deterministic selection
	 * @return string Enhanced markup
	 */
	private function enhance_generic_city_hub_intro( $markup, $hub_key, $city_slug ) {
		// Find first paragraph block (the intro paragraph)
		// Pattern: <!-- wp:paragraph --> ... <p>TEXT</p> ... <!-- /wp:paragraph -->
		if ( ! preg_match( '/<!-- wp:paragraph[^>]*-->\s*<p[^>]*>(.*?)<\/p>\s*<!-- \/wp:paragraph -->/s', $markup, $matches, PREG_OFFSET_CAPTURE ) ) {
			// No paragraph found, nothing to enhance
			return $markup;
		}
		
		$full_block = $matches[0][0];
		$paragraph_text = $matches[1][0];
		$block_position = $matches[0][1];
		
		// Strip HTML tags for analysis
		$text_for_analysis = wp_strip_all_tags( $paragraph_text );
		
		// Check if paragraph is generic
		if ( ! $this->is_generic_intro_paragraph( $text_for_analysis ) ) {
			// Paragraph is already good, no enhancement needed
			return $markup;
		}
		
		// Select enhancement sentence deterministically
		$templates = $this->get_intro_enhancement_templates();
		$hash = md5( $hub_key . '_' . $city_slug );
		$index = hexdec( substr( $hash, 0, 8 ) ) % count( $templates );
		$enhancement_sentence = $templates[ $index ];
		
		// Append enhancement sentence to paragraph content
		// Remove closing </p> tag, add space + enhancement, then close
		$enhanced_paragraph_text = rtrim( $paragraph_text );
		if ( substr( $enhanced_paragraph_text, -4 ) === '</p>' ) {
			$enhanced_paragraph_text = substr( $enhanced_paragraph_text, 0, -4 );
		}
		$enhanced_paragraph_text .= ' ' . esc_html( $enhancement_sentence ) . '</p>';
		
		// Replace original paragraph with enhanced version
		$enhanced_block = str_replace( $paragraph_text, $enhanced_paragraph_text, $full_block );
		$markup = substr_replace( $markup, $enhanced_block, $block_position, strlen( $full_block ) );
		
		return $markup;
	}

	/**
	 * Callback for removing service list blocks
	 * 
	 * Only removes list blocks that contain multiple service page links.
	 * 
	 * @param array $matches Regex matches
	 * @return string Empty string to remove, or original match to keep
	 */
	private function remove_service_list_callback( $matches ) {
		// Only remove if it contains multiple service page links
		if ( substr_count( $matches[0], '<a href=' ) >= 2 ) {
			return '';
		}
		return $matches[0];
	}

	/**
	 * Integrate service links section naturally into City Hub content
	 * 
	 * PRIMARY STRATEGY: Replace {{CITY_SERVICE_LINKS}} token with natural HTML.
	 * FALLBACK: Insert after "Services We Offer" heading if token not found.
	 * Also removes duplicates and ensures Why Choose Us is populated.
	 * 
	 * @param string $markup Gutenberg markup
	 * @param string $hub_key Hub key
	 * @param string $city_slug City slug
	 * @param array $city City data array with 'name' and 'state' keys
	 * @return string Enhanced markup with integrated service links section
	 */
	private function integrate_service_links_section( $markup, $hub_key, $city_slug, $city ) {
		$city_name = isset( $city['name'] ) ? $city['name'] : '';
		$state = isset( $city['state'] ) ? $city['state'] : '';
		
		if ( empty( $city_name ) || empty( $hub_key ) || empty( $city_slug ) ) {
			return $markup;
		}
		
		// Check if service links already exist in content
		if ( false !== strpos( $markup, 'seogen-hub-links' ) ) {
			// Service links already present, don't add again
			// But still check for empty Why Choose Us section
			$markup = $this->ensure_why_choose_us_populated( $markup, $city_name );
			return $markup;
		}
		
		// STEP 1: Remove ALL duplicate/redundant service sections
	
		// Remove "Services Available" variations - Gutenberg format
		$markup = preg_replace(
			'/<!-- wp:heading[^>]*-->\s*<h[23][^>]*>Services Available[^<]*<\/h[23]>\s*<!-- \/wp:heading -->/i',
			'',
			$markup
		);
		
		// Remove "Services Available" variations - Plain HTML format
		$markup = preg_replace(
			'/<h[23][^>]*>Services Available[^<]*<\/h[23]>/i',
			'',
			$markup
		);
		
		// Remove "Services Locally" variations - Both formats
		$markup = preg_replace(
			'/(?:<!-- wp:heading[^>]*-->\s*)?<h[23][^>]*>Services (?:Locally|in [^<]+)<\/h[23]>(?:\s*<!-- \/wp:heading -->)?/i',
			'',
			$markup
		);
		
		// Remove redundant bridge paragraphs that commonly duplicate
		$redundant_phrases = array(
			'We provide .* services throughout',
			'We\'re expanding our service coverage',
			'Call us and we\'ll confirm availability',
			'Explore our services in the area',
		);
		
		foreach ( $redundant_phrases as $phrase ) {
			// Gutenberg format
			$markup = preg_replace(
				'/<!-- wp:paragraph[^>]*-->\s*<p[^>]*>' . $phrase . '[^<]*<\/p>\s*<!-- \/wp:paragraph -->/i',
				'',
				$markup
			);
			// Plain HTML format
			$markup = preg_replace(
				'/<p[^>]*>' . $phrase . '[^<]*<\/p>/i',
				'',
				$markup
			);
		}
		
		// Remove any list blocks that contain multiple service page links (duplicates)
		$markup = preg_replace_callback(
			'/<!-- wp:list[^>]*-->\s*<ul[^>]*>(?:\s*<li>.*?<\/li>)*\s*<\/ul>\s*<!-- \/wp:list -->/is',
			array( $this, 'remove_service_list_callback' ),
			$markup
		);
		
		// AGGRESSIVE: Remove standalone <ul> lists with 2+ service links
		$markup = preg_replace_callback(
			'/<ul[^>]*>(?:\s*<li>.*?<\/li>)*\s*<\/ul>/is',
			array( $this, 'remove_service_list_callback' ),
			$markup
		);
		
		// STEP 2: PRIMARY - Replace {{CITY_SERVICE_LINKS}} token if present
		$service_links_html = $this->build_city_service_links_natural_html( $hub_key, $city_slug, $city_name, $state );
		
		// Look for token in paragraph blocks
		if ( preg_match( '/<!-- wp:paragraph[^>]*-->\s*<p[^>]*>{{CITY_SERVICE_LINKS}}<\/p>\s*<!-- \/wp:paragraph -->/i', $markup ) ) {
			// Replace Gutenberg paragraph block containing token
			$markup = preg_replace(
				'/<!-- wp:paragraph[^>]*-->\s*<p[^>]*>{{CITY_SERVICE_LINKS}}<\/p>\s*<!-- \/wp:paragraph -->/i',
				"<!-- wp:html -->\n" . $service_links_html . "\n<!-- /wp:html -->",
				$markup
			);
			$markup = $this->ensure_why_choose_us_populated( $markup, $city_name );
			return $markup;
		}
		
		// Also check for plain paragraph token (no Gutenberg wrapper)
		if ( preg_match( '/<p[^>]*>{{CITY_SERVICE_LINKS}}<\/p>/i', $markup ) ) {
			$markup = preg_replace(
				'/<p[^>]*>{{CITY_SERVICE_LINKS}}<\/p>/i',
				$service_links_html,
				$markup
			);
			$markup = $this->ensure_why_choose_us_populated( $markup, $city_name );
			return $markup;
		}
		
		// STEP 3: FALLBACK - Find "Services We Offer" heading (legacy content)
		$services_pattern = '/(?:<!-- wp:heading[^>]*-->\s*)?<h[23][^>]*>Services We Offer(?:\s+in\s+[^<]+)?<\/h[23]>(?:\s*<!-- \/wp:heading -->)?(\s*(?:<!-- wp:paragraph[^>]*-->\s*)?<p[^>]*>.*?<\/p>(?:\s*<!-- \/wp:paragraph -->)?){0,2}/is';
		
		if ( ! preg_match_all( $services_pattern, $markup, $all_matches, PREG_OFFSET_CAPTURE ) ) {
			// No "Services We Offer" heading found - insert before FAQ
			return $this->insert_service_links_fallback( $markup, $hub_key, $city_slug, $city_name, $state );
		}
		
		// Remove duplicate "Services We Offer" sections (keep first)
		if ( count( $all_matches[0] ) > 1 ) {
			// Remove from last to first (to preserve positions)
			for ( $i = count( $all_matches[0] ) - 1; $i > 0; $i-- ) {
				$match_text = $all_matches[0][$i][0];
				$match_pos = $all_matches[0][$i][1];
				$match_len = strlen( $match_text );
				$markup = substr_replace( $markup, '', $match_pos, $match_len );
			}
		}
		
		// Find the first "Services We Offer" section again (positions may have changed)
		if ( ! preg_match( $services_pattern, $markup, $matches, PREG_OFFSET_CAPTURE ) ) {
			// Something went wrong, use fallback
			return $this->insert_service_links_fallback( $markup, $hub_key, $city_slug, $city_name, $state );
		}
		
		// Insert service links right after the heading and its paragraphs
		$insert_position = $matches[0][1] + strlen( $matches[0][0] );
		
		// Wrap in Gutenberg HTML block
		$service_links_block = "<!-- wp:html -->\n" . $service_links_html . "\n<!-- /wp:html -->";
		
		// Insert right after "Services We Offer" section
		$markup = substr_replace( $markup, "\n\n" . $service_links_block . "\n\n", $insert_position, 0 );
		
		// Ensure "Why Choose Us" section is populated
		$markup = $this->ensure_why_choose_us_populated( $markup, $city_name );
		
		return $markup;
	}
	
	/**
	 * Ensure "Why Choose Us" section is populated with content
	 * 
	 * Checks if "Why Choose Us" heading exists with empty or missing content below it.
	 * If empty, injects fallback bullet points with trade-neutral benefits.
	 * ONLY applies to city_hub pages.
	 * 
	 * @param string $markup Gutenberg markup
	 * @param string $city_name City display name
	 * @return string Enhanced markup with populated Why Choose Us section
	 */
	private function ensure_why_choose_us_populated( $markup, $city_name ) {
		// Find "Why Choose Us" heading
		$pattern = '/<!-- wp:heading[^>]*-->\s*<h2[^>]*>Why Choose Us<\/h2>\s*<!-- \/wp:heading -->/i';
		
		if ( ! preg_match( $pattern, $markup, $matches, PREG_OFFSET_CAPTURE ) ) {
			// No "Why Choose Us" heading found, nothing to fix
			return $markup;
		}
		
		$heading_end_pos = $matches[0][1] + strlen( $matches[0][0] );
		
		// Check what comes after the heading
		// Look for the next heading or block
		$next_content = substr( $markup, $heading_end_pos, 500 );
		
		// If the next block is immediately another heading (no content between), inject fallback
		if ( preg_match( '/^\s*<!-- wp:heading/', $next_content ) ) {
			// Empty section detected - inject fallback bullet points
			$fallback_content = $this->get_why_choose_us_fallback( $city_name );
			$markup = substr_replace( $markup, "\n\n" . $fallback_content . "\n\n", $heading_end_pos, 0 );
		}
		
		return $markup;
	}
	
	/**
	 * Get fallback "Why Choose Us" content
	 * 
	 * Returns ONE paragraph (4-6 sentences) for City Hub pages.
	 * MUST show all 4 moments: discovery, decision, explanation, expectation.
	 * Describes ACTIONS and real job flow, not values or professionalism.
	 * NO bullets, NO fluff, NO "locally".
	 * 
	 * @param string $city_name City display name
	 * @return string Gutenberg paragraph block with fallback content
	 */
	private function get_why_choose_us_fallback( $city_name ) {
		// JOB FLOW UPGRADE: Shows all 4 moments as real actions
		// Discovery: "figuring out whether the issue is isolated or part of something bigger"
		// Decision: "If it's something that can wait, that's said clearly"
		// Explanation: "the reason is explained along with options"
		// Expectation: "When permits or inspections are involved, that's discussed up front"
		$paragraph = "Most jobs start by figuring out whether the issue is isolated or part of something bigger. If it's something that can wait, that's said clearly. If it's likely to cause trouble later, the reason is explained along with options. When permits or inspections are involved, that's discussed up front so there are no surprises. The goal is to leave the work done correctly and make sure the customer understands what changed.";
		
		$output = "<!-- wp:paragraph -->\n";
		$output .= "<p>" . esc_html( $paragraph ) . "</p>\n";
		$output .= "<!-- /wp:paragraph -->";
		
		return $output;
	}
	
	/**
	 * Fallback: Insert service links when no "Services We Offer" heading exists
	 * 
	 * Inserts ONLY the canonical service links block - no extra headings, no separators.
	 * Matches Service Hub placement strategy.
	 * 
	 * @param string $markup Gutenberg markup
	 * @param string $hub_key Hub key
	 * @param string $city_slug City slug
	 * @param string $city_name City display name
	 * @param string $state State abbreviation
	 * @return string Enhanced markup
	 */
	private function insert_service_links_fallback( $markup, $hub_key, $city_slug, $city_name, $state ) {
		// Render ONLY the canonical service links block
		// NO extra "Services We Offer" heading, NO "Services Locally", NO separators
		$service_links_block = $this->render_city_service_links_block( $hub_key, $city_slug, $city_name, $state );
		
		// Insert before FAQ or before last H2 or at end
		$faq_patterns = array(
			'/<!-- wp:heading[^>]*-->\s*<h2[^>]*>.*?FAQ.*?<\/h2>\s*<!-- \/wp:heading -->/i',
			'/<!-- wp:heading[^>]*-->\s*<h2[^>]*>.*?Frequently Asked Questions.*?<\/h2>\s*<!-- \/wp:heading -->/i',
		);
		
		$inserted = false;
		foreach ( $faq_patterns as $pattern ) {
			if ( preg_match( $pattern, $markup, $matches, PREG_OFFSET_CAPTURE ) ) {
				$insert_pos = $matches[0][1];
				$markup = substr_replace( $markup, $service_links_block . "\n\n", $insert_pos, 0 );
				$inserted = true;
				break;
			}
		}
		
		if ( ! $inserted ) {
			// Find last H2 heading (usually "Why Choose Us")
			if ( preg_match_all( '/<!-- wp:heading[^>]*-->\s*<h2[^>]*>/i', $markup, $matches, PREG_OFFSET_CAPTURE ) ) {
				$last_h2_pos = end( $matches[0] )[1];
				$markup = substr_replace( $markup, $service_links_block . "\n\n", $last_h2_pos, 0 );
				$inserted = true;
			}
		}
		
		if ( ! $inserted ) {
			// Append to end as last resort
			$markup .= "\n\n" . $service_links_block;
		}
		
		return $markup;
	}
	
	/**
	 * Get trade-neutral sentence templates for natural service linking
	 * 
	 * 16 templates to ensure variation across cities at scale.
	 * NO "locally", "local property owners", "serving the local area" phrases.
	 * Uses {city}, {link1}, {link2}, {link3}, {link4}, {link5} placeholders.
	 * 
	 * @return array Array of sentence template strings
	 */
	private function get_service_link_sentence_templates() {
		return array(
			'Many homeowners in {city} reach out when they need help with {link1}, {link2}, or {link3}. These pages explain what the work involves and when it makes sense to call a pro.',
			'If you\'re trying to decide between {link1} and {link2}, the guides below walk through common warning signs, typical timelines, and what to expect.',
			'Some projects start simple and uncover bigger issues—pages like {link1} and {link2} can help you get oriented before you schedule service.',
			'For updates and repairs in {city}, the most common starting points are {link1}, {link2}, and {link3}.',
			'People often call about {link1} or {link2} first, then discover related work that makes sense to handle at the same time.',
			'A lot of homes in {city} eventually need work like {link1} or {link2}. The pages below explain what\'s involved and how to know if it\'s urgent.',
			'Common situations we see include {link1}, {link2}, and {link3}. Each page covers typical costs, timelines, and what to watch for.',
			'If you\'re not sure where to start, pages like {link1} and {link2} explain the basics and when to bring in a professional.',
			'Many calls we get are about {link1} or {link2}. These guides walk through what the work looks like and how to prepare.',
			'Homeowners in {city} often need {link1}, {link2}, or {link3} at some point. The pages below explain options and what makes sense for different situations.',
			'For projects like {link1} or {link2}, it helps to understand the scope before you get quotes. The guides below cover the key details.',
			'Whether you need {link1} or {link2}, the pages below explain what to expect, typical warning signs, and when to schedule service.',
			'People researching {link1} or {link2} in {city} often find these pages helpful for understanding timelines, costs, and what the work involves.',
			'Common questions about {link1}, {link2}, and {link3} are covered in the pages below, including when to call a pro versus wait.',
			'If you\'re dealing with {link1} or {link2}, these pages walk through the process, typical costs, and what to ask before hiring.',
			'Many properties in {city} eventually need work like {link1} or {link2}. The guides below help you understand what\'s urgent and what can wait.',
		);
	}
	
	/**
	 * Get clean anchor text for a service link
	 * 
	 * Priority:
	 * 1. Use _seogen_service_name meta if present
	 * 2. Fallback: Clean the title by removing " in {City} | {Business}" patterns
	 * 
	 * @param int $post_id Service page post ID
	 * @return string Clean anchor text
	 */
	private function get_service_anchor_text( $post_id ) {
		// Try service_name meta first
		$service_name = get_post_meta( $post_id, '_seogen_service_name', true );
		if ( ! empty( $service_name ) ) {
			return $service_name;
		}
		
		// Fallback: Clean the title
		$title = get_the_title( $post_id );
		
		// Remove " in {City}" pattern
		$title = preg_replace( '/\s+in\s+[A-Z][^|]+/', '', $title );
		
		// Remove " | {Business Name}" pattern
		$title = preg_replace( '/\s*\|\s*.+$/', '', $title );
		
		return trim( $title );
	}
	
	/**
	 * Render canonical city service links block with natural inline links
	 * 
	 * Returns EXACTLY ONE service links block with:
	 * - Natural sentence with inline service links (using service_name meta)
	 * - Optional clean list of services (capped at 12, using service_name)
	 * - Trade-neutral and professional tone
	 * 
	 * @param string $hub_key Hub key
	 * @param string $city_slug City slug
	 * @param string $city_name City display name
	 * @param string $state State abbreviation
	 * @return string Gutenberg HTML block with service links
	 */
	private function render_city_service_links_block( $hub_key, $city_slug, $city_name, $state ) {
		// Query service pages for this hub + city combination
		$service_pages_query = new WP_Query( array(
			'post_type' => 'service_page',
			'posts_per_page' => -1,
			'orderby' => 'title',
			'order' => 'ASC',
			'meta_query' => array(
				'relation' => 'AND',
				array(
					'key' => '_seogen_page_mode',
					'value' => 'service_city',
					'compare' => '=',
				),
				array(
					'key' => '_seogen_hub_key',
					'value' => $hub_key,
					'compare' => '=',
				),
				array(
					'key' => '_seogen_city_slug',
					'value' => $city_slug,
					'compare' => '=',
				),
			),
		) );
		
		$service_pages = $service_pages_query->posts;
		wp_reset_postdata();
		
		// Use shared helper to render natural links
		$service_links_html = $this->render_natural_city_service_links(
			$service_pages,
			$city_name,
			$state,
			$hub_key,
			$city_slug
		);
		
		// Wrap in Gutenberg HTML block for proper structure
		$output = "<!-- wp:html -->\n";
		$output .= $service_links_html . "\n";
		$output .= "<!-- /wp:html -->";
		
		return $output;
	}
	
	/**
	 * Build natural city service links HTML (SHARED CANONICAL BUILDER)
	 * 
	 * Used by both admin integration and shortcode rendering.
	 * Outputs 1-2 paragraphs with inline service links (NO UL/OL lists).
	 * Deterministically selects from 16 trade-neutral templates.
	 * 
	 * @param string $hub_key Hub key
	 * @param string $city_slug City slug
	 * @param string $city_name City display name
	 * @param string $state State abbreviation
	 * @return string HTML output with natural inline links
	 */
	private function build_city_service_links_natural_html( $hub_key, $city_slug, $city_name, $state ) {
		// Query service_city pages for this hub + city
		$service_pages = get_posts( array(
			'post_type' => 'service_page',
			'posts_per_page' => 20,
			'post_status' => 'publish',
			'meta_query' => array(
				'relation' => 'AND',
				array(
					'key' => '_seogen_page_mode',
					'value' => 'service_city',
					'compare' => '='
				),
				array(
					'key' => '_seogen_hub_key',
					'value' => $hub_key,
					'compare' => '='
				),
				array(
					'key' => '_seogen_city_slug',
					'value' => $city_slug,
					'compare' => '='
				)
			),
			'orderby' => 'title',
			'order' => 'ASC'
		) );
		
		$output = '';
		
		// Admin debug comment with detailed query info
		if ( current_user_can( 'manage_options' ) ) {
			// Get total service_city pages for comparison
			$all_service_city = get_posts( array(
				'post_type' => 'service_page',
				'posts_per_page' => -1,
				'post_status' => 'publish',
				'fields' => 'ids',
				'meta_query' => array(
					array(
						'key' => '_seogen_page_mode',
						'value' => 'service_city',
						'compare' => '='
					)
				)
			) );
			
			$output .= sprintf(
				'<!-- seogen city service links DEBUG: hub_key=%s, city_slug=%s, found=%d, total_service_city_pages=%d -->' . "\n",
				esc_attr( $hub_key ),
				esc_attr( $city_slug ),
				count( $service_pages ),
				count( $all_service_city )
			);
			
			// Sample a few service pages to show their meta values
			if ( ! empty( $all_service_city ) ) {
				$sample_ids = array_slice( $all_service_city, 0, 3 );
				$output .= '<!-- Sample service page meta values:' . "\n";
				foreach ( $sample_ids as $sample_id ) {
					$sample_hub = get_post_meta( $sample_id, '_seogen_hub_key', true );
					$sample_city = get_post_meta( $sample_id, '_seogen_city_slug', true );
					$sample_title = get_the_title( $sample_id );
					$output .= sprintf(
						'  - "%s" (ID:%d): hub_key=%s, city_slug=%s' . "\n",
						esc_attr( $sample_title ),
						$sample_id,
						esc_attr( $sample_hub ? $sample_hub : 'MISSING' ),
						esc_attr( $sample_city ? $sample_city : 'MISSING' )
					);
				}
				$output .= '-->' . "\n";
			}
		}
		
		$output .= '<div class="seogen-hub-links">' . "\n";
		
		if ( empty( $service_pages ) ) {
			// Empty state
			$output .= '  <p>We\'re expanding our service coverage in this area. Call us and we\'ll confirm availability.</p>' . "\n";
		} else {
			// Deterministic template selection using hash
			$templates = $this->get_service_link_sentence_templates();
			$hash = md5( $hub_key . '_' . $city_slug );
			$template_idx = hexdec( substr( $hash, 0, 8 ) ) % count( $templates );
			$template = $templates[ $template_idx ];
			
			// Deterministic service shuffle (so not every city shows same first 3-5)
			$service_count = count( $service_pages );
			$shuffle_seed = hexdec( substr( $hash, 8, 8 ) );
			$shuffled_indices = range( 0, $service_count - 1 );
			
			// Simple deterministic shuffle using hash
			for ( $i = $service_count - 1; $i > 0; $i-- ) {
				$j = ( $shuffle_seed + $i ) % ( $i + 1 );
				$temp = $shuffled_indices[ $i ];
				$shuffled_indices[ $i ] = $shuffled_indices[ $j ];
				$shuffled_indices[ $j ] = $temp;
			}
			
			// Build up to 5 service links using shuffled order
			$link_count = min( $service_count, 5 );
			$service_links = array();
			
			for ( $i = 0; $i < $link_count; $i++ ) {
				$post = $service_pages[ $shuffled_indices[ $i ] ];
				$permalink = get_permalink( $post->ID );
				$anchor_text = $this->get_service_anchor_text( $post->ID );
				$service_links[ $i ] = '<a href="' . esc_url( $permalink ) . '">' . esc_html( $anchor_text ) . '</a>';
			}
			
			// Replace placeholders in template
			$paragraph = $template;
			$paragraph = str_replace( '{city}', esc_html( $city_name ), $paragraph );
			
			// Replace {link1}, {link2}, etc. with actual links
			for ( $i = 0; $i < count( $service_links ); $i++ ) {
				$placeholder = '{link' . ( $i + 1 ) . '}';
				$paragraph = str_replace( $placeholder, $service_links[ $i ], $paragraph );
			}
			
			// Remove any unused placeholders
			$paragraph = preg_replace( '/{link\d+}/', '', $paragraph );
			
			// Output natural paragraph with 2-3 example links
			$output .= '  <p>' . $paragraph . '</p>' . "\n";
			
			// HYBRID APPROACH: Add complete list of ALL services below natural paragraph
			// This exposes full service breadth while keeping human prose above
			$output .= '  <ul>' . "\n";
			foreach ( $service_pages as $post ) {
				$permalink = get_permalink( $post->ID );
				$anchor_text = $this->get_service_anchor_text( $post->ID );
				$output .= '    <li><a href="' . esc_url( $permalink ) . '">' . esc_html( $anchor_text ) . '</a></li>' . "\n";
			}
			$output .= '  </ul>' . "\n";
		}
		
		$output .= '</div>';
		
		return $output;
	}

	/**
	 * Remove service enumeration paragraphs from City Hub content
	 * 
	 * Detects and removes paragraphs that enumerate specific services (doorway-style content).
	 * Looks for patterns like "Our offerings include X, Y, Z" or "We offer A, B, and C".
	 * 
	 * @param string $markup Gutenberg markup
	 * @return string Cleaned markup with service enumeration removed
	 */
	private function remove_service_enumeration_paragraphs( $markup ) {
		// Get services from cache to build detection patterns
		$services = get_option( 'hyper_local_services_cache', array() );
		if ( empty( $services ) || ! is_array( $services ) ) {
			return $markup;
		}
		
		// Build list of service names for detection (lowercase for matching)
		$service_names = array();
		foreach ( $services as $service ) {
			if ( isset( $service['name'] ) ) {
				$service_names[] = strtolower( trim( $service['name'] ) );
			}
		}
		
		if ( empty( $service_names ) ) {
			return $markup;
		}
		
		// Split markup into blocks
		$blocks = preg_split( '/(<!-- wp:[^>]+ -->|<!-- \/wp:[^>]+ -->)/', $markup, -1, PREG_SPLIT_DELIM_CAPTURE );
		
		$output = '';
		$in_paragraph = false;
		$paragraph_content = '';
		$paragraph_open_tag = '';
		
		foreach ( $blocks as $block ) {
			// Detect paragraph block opening
			if ( preg_match( '/^<!-- wp:paragraph/', $block ) ) {
				$in_paragraph = true;
				$paragraph_content = '';
				$paragraph_open_tag = $block;
				continue;
			}
			
			// Detect paragraph block closing
			if ( $in_paragraph && preg_match( '/^<!-- \/wp:paragraph/', $block ) ) {
				$in_paragraph = false;
				
				// Check if this paragraph enumerates services
				$is_enumeration = $this->is_service_enumeration_paragraph( $paragraph_content, $service_names );
				
				if ( ! $is_enumeration ) {
					// Keep this paragraph
					$output .= $paragraph_open_tag . $paragraph_content . $block;
				}
				// If it IS enumeration, skip it (don't add to output)
				
				continue;
			}
			
			// Collect paragraph content
			if ( $in_paragraph ) {
				$paragraph_content .= $block;
			} else {
				$output .= $block;
			}
		}
		
		return $output;
	}
	
	/**
	 * Check if a paragraph contains service enumeration
	 * 
	 * @param string $content Paragraph content (HTML)
	 * @param array $service_names Array of lowercase service names
	 * @return bool True if paragraph enumerates services
	 */
	private function is_service_enumeration_paragraph( $content, $service_names ) {
		// Strip HTML tags for text analysis
		$text = wp_strip_all_tags( $content );
		$text_lower = strtolower( $text );
		
		// Check for enumeration trigger phrases
		$enumeration_triggers = array(
			'our offerings include',
			'we offer',
			'services include',
			'including',
			'such as',
			'from',
			'range of',
			'everything from',
		);
		
		$has_trigger = false;
		foreach ( $enumeration_triggers as $trigger ) {
			if ( false !== strpos( $text_lower, $trigger ) ) {
				$has_trigger = true;
				break;
			}
		}
		
		if ( ! $has_trigger ) {
			return false;
		}
		
		// Count how many known service names appear in this paragraph
		$service_matches = 0;
		foreach ( $service_names as $service_name ) {
			if ( false !== strpos( $text_lower, $service_name ) ) {
				$service_matches++;
			}
		}
		
		// If paragraph has trigger phrase AND mentions 2+ services, it's enumeration
		return $service_matches >= 2;
	}

	/**
	 * Build parent hub link HTML with clean naming
	 * 
	 * @param string $hub_key Hub key to find parent Service Hub
	 * @return string HTML block or empty string if parent not found
	 */
	private function build_parent_hub_link_html( $hub_key ) {
		$hub_post_id = $this->find_service_hub_post_id( $hub_key );
		if ( $hub_post_id <= 0 ) {
			return '';
		}

		$parent_hub_url = get_permalink( $hub_post_id );
		$parent_hub_title = get_the_title( $hub_post_id );
		
		// Clean title for display: Remove business name, location, and trailing 'Services'
		// Example: "Residential Electrical Services | M Electric" → "Residential Electrical"
		$clean_title = $parent_hub_title;
		
		// Remove business name after pipe
		if ( false !== strpos( $clean_title, '|' ) ) {
			$parts = explode( '|', $clean_title );
			$clean_title = trim( $parts[0] );
		}
		
		// Remove trailing location phrases
		$clean_title = preg_replace( '/\s+(in|near|around|for)\s+[A-Z][^,]+,?\s*[A-Z]{2}$/i', '', $clean_title );
		
		// Remove trailing "Services" or "Service"
		$clean_title = preg_replace( '/\s+services?$/i', '', $clean_title );
		$clean_title = trim( $clean_title );
		
		// Generate link HTML - simple "Back to {Name}" without redundant "services"
		$link_text = '← Back to ' . esc_html( $clean_title );
		$parent_hub_link_html = '<p class="seogen-parent-hub-link"><a href="' . esc_url( $parent_hub_url ) . '">' . $link_text . '</a></p>';
		
		return '<!-- wp:html -->' . $parent_hub_link_html . '<!-- /wp:html -->';
	}

	/**
	 * Inject HTML block immediately after first H1 in Gutenberg markup
	 * 
	 * @param string $markup Gutenberg markup
	 * @param string $html_block HTML block to inject
	 * @return string Modified markup
	 */
	private function inject_after_h1( $markup, $html_block ) {
		if ( empty( $html_block ) ) {
			return $markup;
		}

		// Find first closing </h1> tag
		$h1_close_pos = strpos( $markup, '</h1>' );
		
		if ( false !== $h1_close_pos ) {
			// Insert after </h1> with proper spacing
			$insert_pos = $h1_close_pos + strlen( '</h1>' );
			$markup = substr_replace( $markup, "\n\n" . $html_block . "\n\n", $insert_pos, 0 );
		} else {
			// No H1 found, insert at beginning of content
			$markup = $html_block . "\n\n" . $markup;
		}
		
		return $markup;
	}

	/**
	 * Reduce city name repetition to avoid "scaled footprint" appearance
	 * 
	 * @param string $markup Gutenberg markup
	 * @param array $city City data with 'name' and 'state' keys
	 * @return string Modified markup
	 */
	private function cleanup_city_repetition( $markup, $city ) {
		if ( empty( $city['name'] ) ) {
			return $markup;
		}

		$city_name = $city['name'];
		$state = isset( $city['state'] ) ? $city['state'] : '';
		
		// 1) De-localize headings: "Services We Offer in {City}" → "Services We Offer"
		// Only remove " in {City}" at the end of headings
		$markup = preg_replace(
			'/<h([2-6])>(.*?)\s+in\s+' . preg_quote( $city_name, '/' ) . '<\/h\1>/i',
			'<h$1>$2</h$1>',
			$markup
		);
		
		// 2) Body repetition cap: Replace "In {City}," with "In the area," after first paragraph
		// Find first paragraph closing tag
		$first_p_close = strpos( $markup, '</p>' );
		
		if ( false !== $first_p_close ) {
			// Only apply replacements after first paragraph
			$before_first_p = substr( $markup, 0, $first_p_close + 4 );
			$after_first_p = substr( $markup, $first_p_close + 4 );
			
			// Replace leading "In {City}," patterns with "In the area,"
			$after_first_p = preg_replace(
				'/\bIn\s+' . preg_quote( $city_name, '/' ) . ',\s+/i',
				'In the area, ',
				$after_first_p
			);
			
			// Also replace "in {City}, {State}" in later sections
			if ( ! empty( $state ) ) {
				$after_first_p = preg_replace(
					'/\bin\s+' . preg_quote( $city_name, '/' ) . ',\s*' . preg_quote( $state, '/' ) . '\b/i',
					'in the area',
					$after_first_p
				);
			}
			
			$markup = $before_first_p . $after_first_p;
		}
		
		return $markup;
	}

	/**
	 * Remove duplicate FAQ heading if both "Frequently Asked Questions" and "FAQ" exist
	 * 
	 * @param string $markup Gutenberg markup
	 * @return string Modified markup
	 */
	private function remove_duplicate_faq_heading( $markup ) {
		// Check if "Frequently Asked Questions" heading exists
		$has_full_faq = ( false !== stripos( $markup, 'Frequently Asked Questions' ) );
		
		if ( ! $has_full_faq ) {
			// No duplicate issue, return as-is
			return $markup;
		}
		
		// Remove standalone "FAQ" heading block that appears after "Frequently Asked Questions"
		// Match Gutenberg heading block with just "FAQ"
		$markup = preg_replace(
			'/<!-- wp:heading[^>]*? -->\s*<h[2-6]>FAQ<\/h[2-6]>\s*<!-- \/wp:heading -->/i',
			'',
			$markup,
			1 // Only remove first occurrence
		);
		
		// Also handle plain HTML headings (non-Gutenberg)
		$markup = preg_replace(
			'/<h[2-6]>FAQ<\/h[2-6]>/i',
			'',
			$markup,
			1
		);
		
		return $markup;
	}

	/**
	 * Polish parent hub link markup with editorial context
	 * 
	 * @param string $html Parent hub link HTML
	 * @return string Polished HTML with editorial lead-in
	 */
	private function polish_parent_hub_link_markup( $html ) {
		if ( empty( $html ) ) {
			return $html;
		}
		
		// Add editorial context: "Looking for an overview? ← Back to {Service}"
		// This makes the link feel more natural and less like navigation chrome
		$html = str_replace(
			'<p class="seogen-parent-hub-link"><a href=',
			'<p class="seogen-parent-hub-link">Looking for an overview? <a href=',
			$html
		);
		
		return $html;
	}

	/**
	 * Fix locality replacement artifacts (e.g., "In the area, OK")
	 * 
	 * @param string $markup Gutenberg markup
	 * @return string Fixed markup
	 */
	private function fix_locality_artifacts( $markup ) {
		// Fix broken phrases like "In the area, OK" or "in the area OK"
		// These occur when state abbreviation remains after city name replacement
		
		// Replace "In the area, OK" (and similar state codes) with "Locally,"
		$markup = preg_replace(
			'/\bIn the area,?\s+[A-Z]{2}\b/i',
			'Locally',
			$markup
		);
		
		// Also catch lowercase variants mid-sentence
		$markup = preg_replace(
			'/\bin the area,?\s+[A-Z]{2}\b/',
			'locally',
			$markup
		);
		
		return $markup;
	}

	/**
	 * Reduce generic "any-city" repetition patterns
	 * 
	 * @param string $markup Gutenberg markup
	 * @param array $city City data
	 * @return string Modified markup
	 */
	private function reduce_generic_city_repetition( $markup, $city ) {
		if ( empty( $city['name'] ) ) {
			return $markup;
		}
		
		$city_name = $city['name'];
		
		// Identify generic phrases that signal templated content
		$generic_patterns = array(
			'Choosing local',
			'Our team understands',
			'offers numerous benefits',
			'local expertise',
			'familiar with the area',
		);
		
		// Find ONE paragraph containing both a generic phrase AND the city name
		// Remove city name from that paragraph only (conservative approach)
		foreach ( $generic_patterns as $pattern ) {
			// Match paragraph containing both the pattern and city name
			if ( preg_match( '/<p>([^<]*' . preg_quote( $pattern, '/' ) . '[^<]*' . preg_quote( $city_name, '/' ) . '[^<]*)<\/p>/i', $markup, $matches ) ) {
				$original_p = $matches[0];
				$p_content = $matches[1];
				
				// Remove city name from this paragraph
				$cleaned_content = preg_replace(
					'/\b' . preg_quote( $city_name, '/' ) . '\b/i',
					'',
					$p_content,
					1 // Only first occurrence
				);
				
				// Clean up any double spaces or awkward punctuation
				$cleaned_content = preg_replace( '/\s+/', ' ', $cleaned_content );
				$cleaned_content = preg_replace( '/\s+,/', ',', $cleaned_content );
				$cleaned_content = preg_replace( '/\s+\./', '.', $cleaned_content );
				$cleaned_content = trim( $cleaned_content );
				
				$cleaned_p = '<p>' . $cleaned_content . '</p>';
				$markup = str_replace( $original_p, $cleaned_p, $markup );
				
				// Only rewrite ONE paragraph per page
				break;
			}
		}
		
		return $markup;
	}

	/**
	 * Cleanup FAQ locality references for clarity
	 * 
	 * @param string $markup Gutenberg markup
	 * @param array $city City data
	 * @return string Modified markup
	 */
	private function cleanup_faq_locality( $markup, $city ) {
		if ( empty( $city['name'] ) ) {
			return $markup;
		}
		
		$city_name = $city['name'];
		
		// Find FAQ section (after "Frequently Asked Questions" heading)
		$faq_start = stripos( $markup, 'Frequently Asked Questions' );
		if ( false === $faq_start ) {
			// Try "FAQ" heading
			$faq_start = stripos( $markup, '<h2>FAQ</h2>' );
		}
		
		if ( false === $faq_start ) {
			// No FAQ section found
			return $markup;
		}
		
		// Extract FAQ section (from heading to end of content)
		$before_faq = substr( $markup, 0, $faq_start );
		$faq_section = substr( $markup, $faq_start );
		
		// In FAQ answers only: Remove "in {City}" when it adds no value
		// Keep city references in questions (they're often location-specific)
		// Only remove from answer paragraphs (not from question headings)
		
		// Remove "in {City}" from FAQ answer paragraphs
		$faq_section = preg_replace(
			'/(<p>[^<]*?)\s+in\s+' . preg_quote( $city_name, '/' ) . '\b/i',
			'$1',
			$faq_section
		);
		
		// Remove "in the area" from FAQ answers when it's filler
		$faq_section = preg_replace(
			'/(<p>[^<]*?)\s+in the area\b/i',
			'$1',
			$faq_section
		);
		
		// Clean up any double spaces
		$faq_section = preg_replace( '/\s+/', ' ', $faq_section );
		
		return $before_faq . $faq_section;
	}

	/**
	 * PRIORITY 1: HARD KILL "In the area, OK" BUG (ZERO TOLERANCE)
	 * This is a REQUIRED post-generation cleanup pass - NOT best-effort
	 * This bug must NEVER appear in final output - NO EXCEPTIONS
	 * 
	 * @param string $markup Gutenberg markup
	 * @return string Fixed markup with zero-tolerance validation
	 */
	private function kill_in_the_area_ok_bug( $markup ) {
		// SCALE SAFETY GUARD: This is a mandatory cleanup pass that runs AFTER all other
		// city-name replacement logic to ensure "In the area, OK" never appears
		// This is NON-NEGOTIABLE and must be enforced programmatically
		
		// Pattern 1: "In the area, OK" at start of sentence → "Locally,"
		$markup = preg_replace(
			'/\bIn the area,?\s+[A-Z]{2}\b([^a-z])/i',
			'Locally$1',
			$markup
		);
		
		// Pattern 2: "in the area, OK" mid-sentence → remove entirely
		$markup = preg_replace(
			'/\s+in the area,?\s+[A-Z]{2}\b/',
			'',
			$markup
		);
		
		// Pattern 3: Catch any remaining "area, OK" patterns (zero-tolerance validation)
		$markup = preg_replace(
			'/\barea,?\s+[A-Z]{2}\b/',
			'area',
			$markup
		);
		
		// Clean up any double spaces or awkward punctuation from removals
		$markup = preg_replace( '/\s+/', ' ', $markup );
		$markup = preg_replace( '/\s+,/', ',', $markup );
		$markup = preg_replace( '/\s+\./', '.', $markup );
		
		// VALIDATION: Assert that "area, OK" does NOT exist anywhere in markup
		// If it still exists, fail the cleanup step and remove the phrase entirely
		if ( false !== stripos( $markup, 'area, OK' ) || false !== stripos( $markup, 'area OK' ) ) {
			// Emergency fallback: Remove any remaining instances
			$markup = str_ireplace( array( 'area, OK', 'area OK' ), 'area', $markup );
		}
		
		return $markup;
	}

	/**
	 * PRIORITY 2: Generate EXACTLY ONE city-specific nuance using gpt-4o-mini
	 * This nuance exists ONLY to break large-scale duplication and add human realism
	 * NO MORE, NO LESS - exactly ONE per City Hub page
	 * 
	 * @param array $city City data with 'name' and 'state'
	 * @param string $vertical Vertical (e.g., 'electrician', 'plumber')
	 * @param string $hub_key Hub key (e.g., 'residential', 'commercial')
	 * @return string City nuance text or empty string if generation fails
	 */
	private function generate_city_nuance_gpt( $city, $vertical, $hub_key ) {
		if ( empty( $city['name'] ) || empty( $city['state'] ) ) {
			return '';
		}
		
		$settings = $this->get_settings();
		$api_key = isset( $settings['openai_api_key'] ) ? $settings['openai_api_key'] : '';
		
		if ( empty( $api_key ) ) {
			return '';
		}
		
		$city_name = $city['name'];
		$state = $city['state'];
		
		// SCALE SAFETY GUARD: Construct prompt for gpt-4o-mini
		// This generates EXACTLY ONE subtle nuance to break duplication patterns
		$prompt = "Provide ONE short, factual, non-specific observation (1 sentence, max 25 words) relevant to {$hub_key} {$vertical} work in {$city_name}, {$state}.\n\nChoose ONE category only:\n- housing age or housing stock patterns\n- common upgrade or repair triggers\n- general permitting or inspection considerations (generic, non-legal)\n\nDo NOT mention neighborhoods, statistics, dates, or the business.\nDo NOT exaggerate.\nReturn plain text only.";
		
		$payload = array(
			'model' => 'gpt-4o-mini',
			'messages' => array(
				array(
					'role' => 'user',
					'content' => $prompt,
				),
			),
			'max_tokens' => 50,
			'temperature' => 0.7,
		);
		
		$response = wp_remote_post(
			'https://api.openai.com/v1/chat/completions',
			array(
				'timeout' => 15,
				'headers' => array(
					'Content-Type' => 'application/json',
					'Authorization' => 'Bearer ' . $api_key,
				),
				'body' => wp_json_encode( $payload ),
			)
		);
		
		if ( is_wp_error( $response ) ) {
			return '';
		}
		
		$code = wp_remote_retrieve_response_code( $response );
		if ( 200 !== $code ) {
			return '';
		}
		
		$body = wp_remote_retrieve_body( $response );
		$data = json_decode( $body, true );
		
		if ( ! isset( $data['choices'][0]['message']['content'] ) ) {
			return '';
		}
		
		$nuance = trim( $data['choices'][0]['message']['content'] );
		
		// VALIDATION: Enforce strict rules for city nuance
		// - Must be 1 sentence, max 25 words, contains city name
		// - City name must appear exactly ONCE
		// - Must not be empty, vague, or redundant
		if ( empty( $nuance ) || strlen( $nuance ) > 200 || stripos( $nuance, $city_name ) === false ) {
			return '';
		}
		
		// Ensure city name appears exactly once (EXACTLY ONE)
		if ( substr_count( strtolower( $nuance ), strtolower( $city_name ) ) !== 1 ) {
			return '';
		}
		
		// Word count validation: max 25 words
		$word_count = str_word_count( $nuance );
		if ( $word_count > 25 ) {
			return '';
		}
		
		return $nuance;
	}

	/**
	 * Insert city nuance after first intro paragraph
	 * ENFORCES: EXACTLY ONE nuance paragraph per City Hub page (NO MORE, NO LESS)
	 * 
	 * @param string $markup Gutenberg markup
	 * @param string $nuance_text City nuance text
	 * @return string Modified markup
	 */
	private function insert_city_nuance_after_intro( $markup, $nuance_text ) {
		if ( empty( $nuance_text ) ) {
			return $markup;
		}
		
		// SCALE SAFETY GUARD: Check if nuance already exists (prevent duplicates)
		if ( false !== strpos( $markup, 'seogen-city-nuance' ) ) {
			// Nuance already inserted, do not add another
			return $markup;
		}
		
		// Find first paragraph closing tag (after H1 and parent hub link)
		$first_p_close = strpos( $markup, '</p>' );
		
		if ( false === $first_p_close ) {
			return $markup;
		}
		
		// Find second paragraph closing tag (this is the intro paragraph)
		$second_p_close = strpos( $markup, '</p>', $first_p_close + 4 );
		
		if ( false === $second_p_close ) {
			// Only one paragraph found, insert after it
			$second_p_close = $first_p_close;
		}
		
		// Create nuance paragraph as Gutenberg HTML block
		$nuance_block = "\n\n<!-- wp:html --><p class=\"seogen-city-nuance\">" . esc_html( $nuance_text ) . "</p><!-- /wp:html -->\n\n";
		
		// Insert after intro paragraph
		$insert_pos = $second_p_close + 4;
		$markup = substr_replace( $markup, $nuance_block, $insert_pos, 0 );
		
		return $markup;
	}

	/**
	 * PRIORITY 3: Cap generic paragraphs to MAXIMUM ONE per City Hub page
	 * Generic paragraphs are allowed but strictly limited to prevent duplication
	 * 
	 * @param string $markup Gutenberg markup
	 * @param array $city City data
	 * @return string Modified markup
	 */
	private function enforce_single_generic_paragraph( $markup, $city ) {
		if ( empty( $city['name'] ) ) {
			return $markup;
		}
		
		$city_name = $city['name'];
		$state = isset( $city['state'] ) ? $city['state'] : '';
		
		// SCALE SAFETY GUARD: Identify generic phrases that signal templated content
		$generic_patterns = array(
			'Choosing local',
			'Our team understands',
			'offers numerous benefits',
			'There are several benefits',
			'local expertise',
			'familiar with the area',
			'common challenges',
			'hiring professionals',
		);
		
		$generic_count = 0;
		$max_generic_allowed = 1;
		
		// Find all paragraphs containing generic patterns
		foreach ( $generic_patterns as $pattern ) {
			// Match paragraphs containing the generic pattern
			if ( preg_match_all( '/<p>([^<]*' . preg_quote( $pattern, '/' ) . '[^<]*)<\/p>/i', $markup, $matches, PREG_OFFSET_CAPTURE ) ) {
				foreach ( $matches[0] as $match ) {
					$generic_count++;
					
					// If this is beyond the first generic paragraph, remove city name from it
					if ( $generic_count > $max_generic_allowed ) {
						$original_p = $match[0];
						$p_content = $matches[1][ $generic_count - 1 ][0];
						
						// Remove city name and state from this paragraph
						$cleaned_content = preg_replace(
							'/\b' . preg_quote( $city_name, '/' ) . '\b/i',
							'',
							$p_content
						);
						
						if ( ! empty( $state ) ) {
							$cleaned_content = preg_replace(
								'/\b' . preg_quote( $state, '/' ) . '\b/',
								'',
								$cleaned_content
							);
						}
						
						// Clean up double spaces and awkward punctuation
						$cleaned_content = preg_replace( '/\s+/', ' ', $cleaned_content );
						$cleaned_content = preg_replace( '/\s+,/', ',', $cleaned_content );
						$cleaned_content = preg_replace( '/\s+\./', '.', $cleaned_content );
						$cleaned_content = trim( $cleaned_content );
						
						$cleaned_p = '<p>' . $cleaned_content . '</p>';
						$markup = str_replace( $original_p, $cleaned_p, $markup );
					}
				}
			}
		}
		
		return $markup;
	}

	/**
	 * Apply all City Hub quality improvements to Gutenberg markup
	 * INCLUDES THREE MANDATORY SCALE SAFETY GUARDS (NON-NEGOTIABLE)
	 * 
	 * @param string $markup Gutenberg markup
	 * @param string $hub_key Hub key for parent link
	 * @param array $city City data
	 * @param string $vertical Vertical for city nuance generation
	 * @return string Improved markup with scale safety guards enforced
	 */
	private function apply_city_hub_quality_improvements( $markup, $hub_key, $city, $vertical = '' ) {
		// 1) Build parent hub link
		$parent_hub_link = $this->build_parent_hub_link_html( $hub_key );
		
		// 2) Polish parent hub link with editorial context
		$parent_hub_link = $this->polish_parent_hub_link_markup( $parent_hub_link );
		
		// 3) Inject parent hub link after H1
		$markup = $this->inject_after_h1( $markup, $parent_hub_link );
		
		// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
		// PRIORITY 1.5: Remove service enumeration paragraphs (ANTI-DOORWAY GUARD)
		// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
		$markup = $this->remove_service_enumeration_paragraphs( $markup );
		
		// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
		// PRIORITY 1.6: Enhance generic intro paragraphs (LOCAL SEO IMPROVEMENT)
		// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
		// Append explanatory sentence to generic intros to reduce templated feel
		// and add local context. Does NOT replace AI-generated content.
		$markup = $this->enhance_generic_city_hub_intro( $markup, $hub_key, $city['slug'] );
		
		// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
		// PRIORITY 1.7: Integrate service links section naturally (CONTENT COMPOSITION)
		// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
		// Remove redundant "Services We Offer" section and integrate service links
		// with proper heading structure at generation time (not render-time injection).
		// This makes service links feel authored, not dropped in.
		$markup = $this->integrate_service_links_section( $markup, $hub_key, $city['slug'], $city );
		
		// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
		// PRIORITY 2: Add EXACTLY ONE city-specific differentiator (LOCAL SEO + SCALE SAFETY GUARD)
		// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
		// Use deterministic template selection instead of GPT to ensure:
		// 1) Consistent output for same city (no API variance)
		// 2) Different content across cities (reduces doorway-page similarity)
		// 3) No API costs or latency
		$city_name = isset( $city['name'] ) ? $city['name'] : '';
		$city_slug = isset( $city['slug'] ) ? $city['slug'] : '';
		if ( ! empty( $city_name ) && ! empty( $city_slug ) ) {
			$city_differentiator = $this->select_city_differentiator( $hub_key, $city_slug, $city_name, $vertical );
			$markup = $this->insert_city_nuance_after_intro( $markup, $city_differentiator );
		}
		
		// 4) Reduce city name repetition
		$markup = $this->cleanup_city_repetition( $markup, $city );
		
		// 5) Fix locality replacement artifacts ("In the area, OK")
		$markup = $this->fix_locality_artifacts( $markup );
		
		// 6) Reduce generic "any-city" repetition patterns
		$markup = $this->reduce_generic_city_repetition( $markup, $city );
		
		// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
		// PRIORITY 3: Cap generic paragraphs to ONE per page (SCALE SAFETY GUARD)
		// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
		$markup = $this->enforce_single_generic_paragraph( $markup, $city );
		
		// 7) Cleanup FAQ locality references
		$markup = $this->cleanup_faq_locality( $markup, $city );
		
		// 8) Remove duplicate FAQ heading
		$markup = $this->remove_duplicate_faq_heading( $markup );
		
		// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
		// PRIORITY 1: HARD KILL "In the area, OK" bug (ZERO TOLERANCE - SCALE SAFETY GUARD)
		// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
		$markup = $this->kill_in_the_area_ok_bug( $markup );
		
		return $markup;
	}
}
